version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-popper
    versions:
    - 1.3.10
    - 1.3.9
    - 2.2.3
  - dependency-name: gatsby-plugin-offline
    versions:
    - 3.10.0
    - 3.10.1
    - 3.9.0
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.13.2
    - 2.13.3
    - 2.14.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
