// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_content_delivery_bucket": "dev.finitemonkeys.org",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://dev.finitemonkeys.org.s3-website.us-east-2.amazonaws.com"
};


export default awsmobile;
