// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_content_delivery_bucket": "finitemonkeys.org",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "https://d37l60t353qol2.cloudfront.net"
};


export default awsmobile;
